<%@ Page Title="管理用户信息" Language="C#"  MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeFile="Index.aspx.cs" Inherits="Admin_UserManage" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <p style="font-size: x-large">
        <strong>输入要搜索的视频信息：</strong></p>
    <p style="font-size: x-large" class="text-center">
        <asp:TextBox ID="TextBox2" runat="server" style="font-size: small" Width="189px"></asp:TextBox>
        <asp:DropDownList ID="DropDownList2" runat="server" style="font-size: small">
            <asp:ListItem Selected="True">ID</asp:ListItem>
            <asp:ListItem>标题</asp:ListItem>
            <asp:ListItem>分类</asp:ListItem>
            <asp:ListItem>上传者</asp:ListItem>
        </asp:DropDownList>
        <asp:Button ID="SearchVideo" runat="server" style="font-size: small" Text="搜索" OnClick="SearchVideo_Click" />
    </p>
    <p style="font-size: x-large" class="text-center">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2" Width="679px" OnRowDeleting="GridView1_RowDeleting">
            <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
            <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
            <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FFF1D4" />
            <SortedAscendingHeaderStyle BackColor="#B95C30" />
            <SortedDescendingCellStyle BackColor="#F1E5CE" />
            <SortedDescendingHeaderStyle BackColor="#93451F" />
        </asp:GridView>
    </p>
    
</asp:Content>

